import Navbar from "./components/Navbar";
import MoviesProvider from "./context/moviesContext";
import './globals.css'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MoviesProvider>
      <body>
        <header>
          <Navbar >
            {children}
          </Navbar>
        </header>
        {/* {children} */}
      </body>
        </MoviesProvider>
    </html>
  );
}
